#!/usr/bin/env bash
set -euo pipefail

TOKEN='wave_UK_lj_DH1'
ENDPOINT='https://api.wave.com/submit_resume'

WORKDIR="$(mktemp -d)"
#trap 'rm -rf "$WORKDIR"' EXIT

RESUME_TXT="$WORKDIR/resume.txt"
COVER_TXT="$WORKDIR/cover_letter.txt"
QANDA_TXT="$WORKDIR/qanda.txt"
JSON_OUT="$WORKDIR/wave_submit.json"
RESP_OUT="$WORKDIR/response.out"

cat > "$RESUME_TXT" <<'EOF'
Ljubomir JOSIFOVSKI
https://ljubomirj.github.io
LjubomirJosifovski@gmail.com
+44-7910-850-111
11 Pendennis Court, Harpenden AL5 1SG, UK

Summary
ML/AI researcher and engineer in industrial R&D, with background spanning speech recognition, quantitative research, trading and portfolio management, and machine learning systems. Experience building research platforms and production systems across forecasting, optimisation, and large-scale data-driven modelling.

Now: train-time and test-time reasoning in LLM systems, applying ideas from structured search and hypothesis management developed in ASR lattice decoding. Interested in agentic workflows, programmatic prompting (DSPy), and building higher-level computational systems where dialogue becomes an executable specification treating RLM inference as compute and context as working memory, with explicit mechanisms for branching, verification, stopping.

Prior: quantitative researcher, trader and portfolio manager developing systematic equity and FX models including low SNR signal extraction, fitting, forecasting, portfolio optimisation, trading and risk management.

Earlier: PhD research in robust speech recognition in noise, MSc in text-to-speech synthesis and spoken document retrieval. Background in applied mathematics, statistics, computer science, and industrial R&D.

Skills
Programming: C/C++/OpenMP, Python, SQL, DuckDB, bash, awk, make, gdb/ddd, MATLAB, C#, R, Java.
Agents: Codex/Claude/Cursor/Gemini/Cline; local LLM workflows LMStudio/llama.cpp
Tools: Vim, Git, Github, screen, VSCode, CLion, Jupyter, Spyder, MATLAB, Bloomberg/Reuters API-s.
Platforms: Linux (Ubuntu, CentOS), MacOS, MS-Windows, Gcloud, Slurm, HTCondor, Unix.

Experience
F9 Research, Director (2016–present; Harpenden, UK; remote distributed US, UK, EU)
Rekindled ML/AI interests with OSS llama.cpp, open weights local LLMs, agents for coding and data (text2sql).
DNNs for tabular data forecasting (c.f. Hugging Face TabArena) using TabM, TabPFN for regression.
LLM APIs for earnings calls doc2vec feature extraction for modelling and forecasting.
Quant research and development on short-horizon strategies using Python, C++, cluster and cloud resources.
Managed and traded a market-neutral book gross ~$350M, trading ~$35M daily in EU and US markets.

FutureSearch, Research Scientist (2025; remote distributed US, UK, EU)
Created and used agents to gather and organise financial data for end-user would-be products, and for internal use.
Consulted on using the presumed 'alpha' generated by the AI agent(s) for potential investment.

Marshall Wace, Senior Quantitative Researcher (2010–2016; London, UK)
Developed and scaled market-neutral portfolios from $100M to $10B+ over a period of 6 years.
Pioneered and wrote unified R&D frameworks for data ingestion, signal extraction, modelling, forecasting, portfolio optimisation, simulation, execution, and reproducible research workflows. Mentored junior researchers.

Credit Suisse, Quantitative Analyst (2007–2009; London, UK)
Independently traded equity market-neutral portfolios systematically, achieving 18% lifetime returns with Sharpe 3.1.
Built and operated a complete trading platform for multi-market European equities.

G-Research (DPFMG), Quantitative Analyst (2004–2007; London, UK)
Designed and implemented systematic trading models for global equities and FX for fund profitability.
Modelling, forecasting, risk management, and multi-period optimisation for mid- and high-frequency trading strategies.
Operational portfolio management and production monitoring, including on-call duty.

Canon Research Europe, Researcher (2001–2004; Bracknell, UK)
Embedded automatic speech recognition, indexing, and retrieval of spoken documents with speech.

Education
Ph.D., Computer Science – University of Sheffield, UK (2000)
Thesis: Robust Speech Recognition with Missing and Unreliable Data

M.Phil., Electrical Engineering – University Sv. Kiril i Metodij, Skopje, MK (1997)
Thesis: System for Text-to-Speech Conversion for the Macedonian Language

B.S., Electrical Engineering – University Sv. Kiril i Metodij, Skopje, MK (1993)
EOF

cat > "$COVER_TXT" <<'EOF'
Hi there,

Your “boring strategy” immediately resonated with me:

> We like boring technology. We favor tools that are reliable, well-understood, and easy to debug.
> Simplicity is a strategy.

I share that instinct. I generally prefer proven tools and solid engineering practices unless there is a strong reason not to. One of my favourite programming books is Writing Solid Code, and I have come to believe that writing boring code is writing solid code.

I’m an ML/AI researcher and engineer in industrial R&D, with earlier work in speech and language technology and a long second career in quantitative research and systematic trading. More recently, I built and used AI agents for internal data workflows, and I’m now spending much of my time working with coding agents, local LLMs, and agentic tools — and, to be honest, having a great deal of fun doing so. My current interests include intelligent editing tools with speech input and built-in intelligence that can often do the right thing with minimal friction, chemistry text2sql/data-agent workflows, and practical ways of making LLM systems more interactive and useful.

Earlier in my career I worked on ASR, TTS, and spoken document retrieval, including a PhD in robust speech recognition in noise, research at Canon on embedded ASR and speech retrieval, and work at Motorola on distributed speech recognition. That background gave me a lasting interest in systems that combine modelling, inference, interactivity, and real-world constraints.

The parts of my background most relevant to this role are recent agent/data-workflow work at FutureSearch; earlier embedded ASR, speech retrieval, and lattice-based search work at Canon; distributed speech recognition work at Motorola; and PhD/MSc research in robust ASR and TTS.

I’m based in Harpenden, UK, and currently work from a home office/lab. I’m set up via a UK limited company and am flexible on engagement structure.

Relevant links:
Email: LjubomirJosifovski@gmail.com
LinkedIn: https://www.linkedin.com/in/ljubomirjosifovski
F9 RESEARCH LTD: https://find-and-update.company-information.service.gov.uk/company/10173069
CV: https://ljubomirj.github.io/ljcv.pdf
Bio: https://ljubomirj.github.io/ljbio.pdf
Home: https://ljubomirj.github.io
GitHub: https://github.com/ljubomirj

Thank you for your time and consideration.

Kind regards,
Ljubomir Josifovski
EOF

cat > "$QANDA_TXT" <<'EOF'
Q: What's the hardest production failure you've debugged in an ML system, and how did you fix it?

A:
A memorable one was in a live quantitative trading system where the production code was picking up data from the wrong 10-minute interval for the Tokyo market because of a timezone mismatch. It was awkward to debug because most of the production and simulation code was shared, so the bug only showed up in a narrow live path. I tracked it down by reasoning through the code carefully and then building synthetic test cases that made the failure obvious. Once the cause was clear, the fix itself was simple. The more important part was adding checks and tests around that path so the same class of issue would be much easier to catch next time.

Q: Describe your experience with product A/B tests, optimization, and exploratory data analysis.

A:
Most of my work has not been classic internet-scale product A/B testing; it has been more on the research, modelling, and production side. Where I do have strong experience is exploratory data analysis and optimisation in quantitative research and ML settings. When looking at a new dataset or feature source, I usually start with basic coverage, integrity, and summary analysis, then try to understand how it aligns with existing data and whether it adds genuine signal in modelling across different horizons or use cases. A lot of my work over the years has really been this kind of empirical optimisation: testing ideas, measuring what actually improves things, and refining models and pipelines based on evidence rather than wishful thinking.
EOF

jq -n \
  --arg submitted_at "$(date -u +%FT%TZ)" \
  --arg name "Ljubomir Josifovski" \
  --arg email "ljubomirjosifovski@gmail.com" \
  --arg phone "+44 7910 850111" \
  --arg location "Harpenden, UK" \
  --arg role_title "Applied AI Scientist - LLMs & Voice" \
  --arg job_url "https://www.wave.com/en/careers/job/5779974004/" \
  --arg linkedin "https://www.linkedin.com/in/ljubomirjosifovski" \
  --arg f9research "https://find-and-update.company-information.service.gov.uk/company/10173069" \
  --arg website "https://ljubomirj.github.io" \
  --arg github "https://github.com/ljubomirj" \
  --arg cv_pdf_filename "cvlj97s2.pdf" \
  --arg bio_pdf_filename "cvlj97.pdf" \
  --rawfile resume_text "$RESUME_TXT" \
  --rawfile cover_letter_text "$COVER_TXT" \
  --rawfile qanda_text "$QANDA_TXT" \
  '{
    submitted_at: $submitted_at,
    candidate: {
      name: $name,
      email: $email,
      phone: $phone,
      location: $location
    },
    application: {
      role_title: $role_title,
      job_url: $job_url
    },
    links: {
      linkedin: $linkedin,
      f9research: $f9research,
      website: $website,
      github: $github,
      cv_pdf: "https://ljubomirj.github.io/ljcv.pdf",
      bio_pdf: "https://ljubomirj.github.io/ljbio.pdf"
    },
    files: {
      cv_pdf_filename: $cv_pdf_filename,
      bio_pdf_filename: $bio_pdf_filename
    },
    materials: {
      resume_text: $resume_text,
      cover_letter_text: $cover_letter_text,
      application_q_and_a_text: $qanda_text
    }
  }' > "$JSON_OUT"

echo "== JSON preview =="
cat "$JSON_OUT"
echo
echo "== POSTing to $ENDPOINT =="

HTTP_CODE="$(
  curl -sS \
    -o "$RESP_OUT" \
    -w '%{http_code}' \
    -X POST "$ENDPOINT" \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "Content-Type: application/json" \
    --data-binary @"$JSON_OUT"
)"

echo "HTTP status: $HTTP_CODE"
echo "Response body:"

if jq -e . "$RESP_OUT" >/dev/null 2>&1; then
  jq . "$RESP_OUT"
else
  cat "$RESP_OUT"
fi
echo

# Fail on non-2xx HTTP status
if [[ ! "$HTTP_CODE" =~ ^2 ]]; then
  echo "Submission failed: non-2xx HTTP status." >&2
  echo "Response saved at: $RESP_OUT" >&2
  exit 1
fi

# Fail on application-level JSON error payloads, e.g. {"code":"...","message":"..."}
if jq -e 'type == "object" and has("code") and (.code | type == "string") and (.code != "")' "$RESP_OUT" >/dev/null 2>&1; then
  echo "Submission failed: API returned an application error." >&2
  echo "Response saved at: $RESP_OUT" >&2
  exit 1
fi

echo "Submission appears successful."
echo "Response saved at: $RESP_OUT"

